[package]
name = "bevy_impulse"
version = "0.0.1"
edition = "2021"
authors = ["Grey <mxgrey@intrinsic.ai>"]
license = "Apache-2.0"
description = "Reactive programming and workflow execution for bevy"
readme = "README.md"
repository = "https://github.com/open-rmf/bevy_impulse"
keywords = ["reactive", "workflow", "behavior", "agent", "bevy"]
categories = [
  "science::robotics",
  "asynchronous",
  "concurrency",
  "game-development",
]

[dependencies]
bevy_impulse_derive = { path = "macros", version = "0.0.1" }
bevy_ecs = "0.12"
bevy_utils = "0.12"
bevy_hierarchy = "0.12"
bevy_derive = "0.12"
bevy_app = "0.12"

async-task = { version = "4.7.1", optional = true }

# TODO(@mxgrey) We could probably remove bevy_tasks when the single_threaded_async
# feature is active, but we'd have to refactor some internal usage of
# bevy_tasks::Task, so we're leaving it as a mandatory dependency for now.
bevy_tasks = { version = "0.12", features = ["multi-threaded"] }

arrayvec = "0.7"
itertools = "0.13"
smallvec = "1.13"
tokio = { version = "1.39", features = ["sync"] }
futures = "0.3"
backtrace = "0.3"
anyhow = "1.0"
thiserror = "1.0"

# These dependencies are only used by the testing module.
# We may want to consider feature-gating them, but we use
# the testing module for doctests, and doctests can only
# make use of default features, so we're a bit stuck with
# these for now.
bevy_core = "0.12"
bevy_time = "0.12"

schemars = { version = "0.8.21", optional = true }
serde = { version = "1.0.210", features = ["derive"], optional = true }
serde_json = { version = "1.0.128", optional = true }
log = "0.4.22"

[features]
single_threaded_async = ["dep:async-task"]
diagram = ["dep:schemars", "dep:serde", "dep:serde_json"]

[dev-dependencies]
async-std = { version = "1.12" }
test-log = "0.2.16"

[workspace]

[[bin]]
name = "generate_schema"
path = "src/diagram/generate_schema.rs"
required-features = ["diagram"]
doc = false
