[package]
name = "bevy_impulse"
version = "0.2.0"
edition = "2021"
authors = ["Grey <mxgrey@intrinsic.ai>"]

[dependencies]
bevy_impulse_derive = { path = "macros" }
bevy_ecs = "0.14"
bevy_utils = "0.14"
bevy_hierarchy = "0.14"
bevy_derive = "0.14"
bevy_app = "0.14"

async-task = { version = "4.7.1", optional = true }

# TODO(@mxgrey) We could probably remove bevy_tasks when the single_threaded_async
# feature is active, but we'd have to refactor some internal usage of
# bevy_tasks::Task, so we're leaving it as a mandatory dependency for now.
bevy_tasks = { version = "0.14", features = ["multi_threaded"] }

arrayvec = "*"
itertools = "*"
smallvec = "*"
tokio = { version = "*", features = ["sync"]}
futures = "0.3"
backtrace = "0.3"
anyhow = "*"
thiserror = "*"

# These dependencies are only used by the testing module.
# We may want to consider feature-gating them, but we use
# the testing module for doctests, and doctests can only
# make use of default features, so we're a bit stuck with
# these for now.
bevy_core = "0.14"
bevy_time = "0.14"

[features]
single_threaded_async = ["dep:async-task"]

[dev-dependencies]
async-std = { version = "*" }
