// Generated from registry.schema.json (sha1:f01e52c65ee1e6bad1790653b8a5ae239b581fab)
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Schema =
  | {
      [k: string]: unknown;
    }
  | boolean;

export interface DiagramElementRegistry {
  messages: {
    [k: string]: MessageRegistration;
  };
  nodes: {
    [k: string]: NodeRegistration;
  };
  schemas: {
    [k: string]: unknown;
  };
  sections: {
    [k: string]: SectionRegistration;
  };
  [k: string]: unknown;
}
export interface MessageRegistration {
  operations: MessageOperation;
  schema?: Schema | null;
  type_name: string;
  [k: string]: unknown;
}
export interface MessageOperation {
  deserialize?: {
    [k: string]: unknown;
  } | null;
  fork_clone?: {
    [k: string]: unknown;
  } | null;
  fork_result?: {
    [k: string]: unknown;
  } | null;
  join?: {
    [k: string]: unknown;
  } | null;
  serialize?: {
    [k: string]: unknown;
  } | null;
  split?: {
    [k: string]: unknown;
  } | null;
  unzip?: string[] | null;
  [k: string]: unknown;
}
export interface NodeRegistration {
  $key$: string;
  config_schema: Schema;
  name: string;
  request: string;
  response: string;
  [k: string]: unknown;
}
export interface SectionRegistration {
  config_schema: Schema;
  metadata: SectionMetadata;
  name: string;
  [k: string]: unknown;
}
export interface SectionMetadata {
  buffers: {
    [k: string]: SectionBuffer;
  };
  inputs: {
    [k: string]: SectionInput;
  };
  outputs: {
    [k: string]: SectionOutput;
  };
  [k: string]: unknown;
}
export interface SectionBuffer {
  item_type?: string | null;
  [k: string]: unknown;
}
export interface SectionInput {
  message_type: string;
  [k: string]: unknown;
}
export interface SectionOutput {
  message_type: string;
  [k: string]: unknown;
}
