[package]
name = "calculator"
version = "0.0.1"
edition = "2021"

[dependencies]
crossflow_diagram_editor = { path = "../../../diagram-editor", features = ["basic_executor"] }
calculator_ops_catalog = { path = "../calculator_ops_catalog" }

[dev-dependencies]
assert_cmd = "2.0.16"
