[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = "0.12"
bevy_core = "0.12"
bevy_impulse = { version = "0.0.2", path = "../../..", features = ["diagram"] }
bevy_time = "0.12"
serde_json = "1.0.128"
tracing-subscriber = "0.3.19"
