name: ci_linux

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # The final 1 indicates that we want to run this test on Tuesdays, making
    # this a weekly test.
    - cron:  '30 2 * * 1'
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        rust-version: [stable]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup rust
      run: rustup default ${{ matrix.rust-version }}

    - name: Build default features
      run: cargo build --workspace
    - name: Test default features
      run: cargo test --workspace

    - name: Test diagram
      run: cargo test --workspace -F=diagram

    - name: Build single_threaded_async
      run: cargo build --features single_threaded_async
    - name: Test single_threaded_async
      run: cargo test --features single_threaded_async

    - name: Build docs
      run: cargo doc --all-features

