name: ci_web

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # The final 1 indicates that we want to run this test on Tuesdays, making
    # this a weekly test.
    - cron:  '30 2 * * 1'
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Add wasm32 target
      run: rustup target add wasm32-unknown-unknown

    - uses: actions/checkout@v3

    - name: Build package
      run: cargo build --target wasm32-unknown-unknown --release --features single_threaded_async

    # Notes:
    # * Targeting wasm32 only works with the single_threaded_async feature because
    #   wasm32 doesn't support threading at the moment.
    # * The regular cargo test pipeline cannot run tests that were compiled to wasm.
    #   There may be ways to develop test executables specific to wasm32, but this
    #   seems like overkill for now.
