name: style

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  style:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: rustfmt
      run: |
        rustup component add rustfmt

    - name: style
      run: cargo fmt --all --check

    - name: default features check
      run: cargo check

    - name: single_threaded_async check
      run: cargo check --features single_threaded_async

    - name: clippy
      run: cargo clippy
